set autoindent
set smartindent
set expandtab
set tabstop=4
set	shiftwidth=4
syntax enable
set ruler
set wildmenu
set number
set mouse=a
set title
set background=dark
set backspace=indent,eol,start
set history=1000
set noswapfile
