daysOfCode = [
    '001 - Variables to Manage Data',
    '002 - Data Types and How to Manipulate Strings',
    '003 - Control Flow and Logical Operators',
    '004 - Randomisation and Python Lists',
    '005 - Python Loops',
    '006 - Python Functions & Karel',
    '007 - Hangman',
    '008 - Function Parameters & Caesar Cipher',
    '009 - Dictionaries, Nesting, and the Secret Auction',
    '010 - Functions with Outputs',
    '011 - Blackjack Capstone Project',
    '012 - Scope and Number Guessing Game',
    '013 - Debugging',
    '014 - Higher Lower Game Project',
    '015 - The Coffee Machine',
    '016 - Object Oriented Programming (OOP)',
    '017 - The Quiz Project',
]
