#!/usr/bin/env python3
import sys
import os
if len(sys.argv) < 2:
    print('Syntax: pynew filename')
    sys.exit()
filename = sys.argv[1]
filename += '.py'
with open(filename, 'w') as f:
    f.write('#!/usr/bin/env python3\n\n')
os.system('chmod +x ' + filename)
