#!/usr/bin/env python3
import sys
import os
if len(sys.argv) < 2:
    print('Syntax: pynew filename')
    sys.exit()
filename = sys.argv[1]
filename += '.py'
with open(filename, 'w') as f:
    f.write('''#!/usr/bin/env python3
import os

def clear():
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')

''')
os.system('chmod +x ' + filename)
