#!/usr/bin/env python3
from sys import argv, exit
from os import name, system
if len(argv) < 2:
    print('Syntax: pynew filename')
    exit()
filename = argv[1]
filename += '.py'
with open(filename, 'w') as f:
    f.write('''#!/usr/bin/env python3
import os


def clear():
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')


clear()
''')
system('chmod +x ' + filename)
